"""add qa column

Revision ID: 51ef70910121
Revises: fc79d4870ea6
Create Date: 2022-08-03 23:15:27.838400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ef70910121'
down_revision = 'fc79d4870ea6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_race_summary', sa.Column('qa_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_race_summary', 'qa_done')
    # ### end Alembic commands ###
