"""add stint summary

Revision ID: 876d02cbb5c4
Revises: dc7ef0937857
Create Date: 2022-08-26 20:23:58.092651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d02cbb5c4'
down_revision = 'dc7ef0937857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stint_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_race_summary_id', sa.Integer(), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.Column('average_time', sa.Interval(), nullable=True),
    sa.Column('fastest_lap', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.Interval(), nullable=True),
    sa.Column('lap_count', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_race_summary_id'], ['driver_race_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stint_summary')
    # ### end Alembic commands ###
