"""add race time

Revision ID: 8a74d36061e4
Revises: 51ef70910121
Create Date: 2022-08-20 08:58:34.878516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a74d36061e4'
down_revision = '51ef70910121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_race_summary', sa.Column('time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_race_summary', 'time')
    # ### end Alembic commands ###
